CREATE TRIGGER DELETE_ListItems
	ON ListItems
	INSTEAD OF DELETE
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM ActionAdventureShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM AnimationShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM AnimeShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM AnthologyShows WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM ComedyShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM CrimeShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM DocumentaryShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM DramaShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM FamilyShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM FantasyMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM HistoricalDramaShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM HistoryShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM HorrorShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM KidsShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM MedicalDramaShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM MysteryShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM RomanceShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM ScifiShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM SitcomShows WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM TeenDramaShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM ThrillerShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM TrendingShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM WarShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM WesternShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM WorkplaceComedyShowsAndMovies WHERE ListItemId IN (SELECT ID FROM DELETED)
	DELETE FROM ListItems WHERE ID IN (SELECT ID FROM DELETED) /* necessary, because trigger is an INSTEAD OF trigger */
end;
