CREATE TRIGGER DELETE_Snapshot
	ON Snapshots
	INSTEAD OF DELETE
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM ActionAdventureShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM AnimationShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM AnimeShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM AnthologyShows WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM ComedyShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM CrimeShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM DocumentaryShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM DramaShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM FamilyShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM FantasyMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM HistoricalDramaShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM HistoryShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM HorrorShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM KidsShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM MedicalDramaShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM MysteryShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM RomanceShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM ScifiShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM SitcomShows WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM TeenDramaShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM ThrillerShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM TrendingShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM WarShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM WesternShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM WorkplaceComedyShowsAndMovies WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM ListItems WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM MovieGenres WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM ShowGenres WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM Configurations WHERE SnapshotId IN (SELECT ID FROM DELETED)
	DELETE FROM Snapshots WHERE ID IN (SELECT ID FROM DELETED) /* necessary, because trigger is an INSTEAD OF trigger */
end;
